### ISSUE TITLE
Reuse RecordType in Collection and enforce type

### ISSUE THREAD

**Issue by nhovratov** [FriendsOfTYPO3/content-blocks#101]
```
-
  identifier: relations
  type: Collection
  foreign_table: tx_dsboilerplate_contentblockrelation
  shareAcrossTables: true
  shareAcrossFields: true
  overrideChildTca:
    columns:
      type:
        config:
          default: dsboilerplate_linktiles_test
          readOnly: true
  foreign_match_fields:
    type: dsboilerplate_linktiles_test
-
  identifier: relations2
  type: Collection
  foreign_table: tx_dsboilerplate_contentblockrelation
  shareAcrossTables: true
  shareAcrossFields: true
  overrideChildTca:
    columns:
      type:
        config:
          default: dsboilerplate_linktiles_test2
          readOnly: true
  foreign_match_fields:
    type: dsboilerplate_linktiles_test2
```

![Screenshot 2024-01-26 at 21-41-13 Edit Page Content No title on page Home · Content Blocks TYPO3 CMS 12 4 10](https://github.com/nhovratov/content-blocks/assets/19343425/902320bc-c7dc-4e6b-be2c-109ac179c553)
