### ISSUE TITLE
Allow to omit `label` for select items as they can be defined now in Labels.xlf

### ISSUE THREAD

**Issue by nhovratov** [FriendsOfTYPO3/content-blocks#108]

**Comment by PKuhlmay** [comment]
For me it was a little bit confusing, when I used the command "content-blocks:language:generate". This command also generated labels inside my Labels.xlf file. I then wanted to remove the labels option inside my select configuration:

```
    fields:
      - identifier: rows_count
        type: Select
        default: 3
        renderType: selectSingle
        items:
          - value: 1
          - value: 2
          - value: 3
          - value: 4
```

This didn't work and I got an error `PHP Warning: Undefined array key 0 in /var/www/html/vendor/typo3/cms-core/Classes/Schema/Struct/SelectItem.php line 49`

So I would appreciate it, if the label for select items is not required anymore.
