### ISSUE TITLE
Prevent adding a label inside Labels.xlf when it is already defined in EditorInterface.yaml

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#109]
I use a select type with some values:

```
renderType: selectSingle
items:
  - label: '1 column'
    value: 1
  - label: '2 columns'
    value: 2
  - label: '3 columns'
    value: 3
  - label: '4 columns'
    value: 4
```

When I now use the command `content-blocks:language:generate` the labels are also included inside my **Labels.xlf** file. These labels have a higher priority (AFAIK).

So when I now want to edit the labels inside my **EditorInterface.yaml** file, I need to remove them from the **Labels.xlf** first, because the changes inside my .yaml file wouldn't have any effect.

**It would be great, if the command only adds the labels, when they are not added inside my .yaml file.**

Could be related to #108
