### ISSUE TITLE
Select item label as integer

### ISSUE THREAD

**Issue by ogrosko** [FriendsOfTYPO3/content-blocks#111]
Hello,
after upgrade to version `0.5.1` (working fine 0.4.0) we received following error in Typo3:

`TYPO3\CMS\Core\Schema\Struct\SelectItem::__construct(): Argument #2 ($label) must be of type string, int given, called in /var/www/html/vendor/typo3/cms-core/Classes/Schema/Struct/SelectItem.php on line 47`

It is caused by following field config:

```
      -
        identifier: elements_in_row
        type: Select
        renderType: selectSingle
        items:
          -
            label: 3
            value: 3
          -
            label: 4
            value: 4
```
Label with integer throws an error.
Following changes in config helped:

```
      -
        identifier: elements_in_row
        type: Select
        renderType: selectSingle
        items:
          -
            label: '3'
            value: 3
          -
            label: '4'
            value: 4
```

I'm not sure whether is it a bug or label should be always wrapped in apostrophes
