### ISSUE TITLE
labelField inside Collection doesn't show the expected values

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#112]
I have the following Collection:

```
  - identifier: podcasts
    type: Collection
    labelField:
      - podcast_episode
      - podcast_date
      - podcast_title
    fields:
      - identifier: podcast_header_settings
        type: Palette
        fields:
        - identifier: podcast_episode
          type: Number
          range:
            lower: 1
        - identifier: podcast_date
          type: DateTime
          format: date
          disableAgeDisplay: false
      - identifier: podcast_title
        type: Text
      - identifier: podcast_description
        type: Textarea
        enableRichtext: true
      - identifier: podcast_link
        type: Link
        allowedTypes:
          - page
```

The problem is, that the configuration for labelField doesn't work as expected. I expected to see the podcast_episode (which is a number), the date and the title. But I get the title, the date and the title. So the title is shown twice.

![Bildschirmfoto 2024-01-31 um 17 34 27](https://github.com/nhovratov/content-blocks/assets/107543296/9447f81f-8ce7-4c92-8feb-c9523fd6ba82)
