### ISSUE TITLE
[DOCS] Add example for Checkbox renderType checkboxLabeledToggle to Docs

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#114]
As discussed in Slack https://typo3.slack.com/archives/C8Z2UM50Q/p1706797413374989

```
items:
    -
        label: 'Your Label'
        labelChecked: 'Checked'
        labelUnchecked: 'Unchecked'
```
