### ISSUE TITLE
DateTime with an upper range always shows validation error

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#13]
I have a DateTime field with an upper range. No matter what I input, I always get a validation error with "max".

Configuration:
```
name: treupo/datetime
group: treupo
prefixFields: true
fields:
  - identifier: max
    type: DateTime
    default: '12:00 2023-02-11'
    range:
      lower: '12:00 2022-01-01'
      upper: '12:00 2050-12-31'
```
![Bildschirmfoto 2023-07-03 um 19 40 45](https://github.com/nhovratov/content-blocks/assets/107543296/5fdc2fb6-a881-4a1b-860f-97a38260c8f9)

![Bildschirmfoto 2023-07-03 um 19 39 15](https://github.com/nhovratov/content-blocks/assets/107543296/e93bae9c-2fd4-454f-bb1c-3ea5ec5fe227)

TYPO3 12.4.2
CB: dev-main

Note: I switched the notation inside the lower and upper definition. The input field stores the datetime with HH:MM YYYY-MM-DD, inside the example in the CB documentation there is: YYYY-MM-DD HH:MM:SS
https://github.com/nhovratov/content-blocks/blob/d1794a17218e9d3ab9ccaff43351fe9e685103d7/Documentation/IntegratorManual/YamlReference/DateTime/Index.rst?plain=1#L110
