### ISSUE TITLE
[BUG] Collection with new table can not be shared across tables or fields

### ISSUE THREAD

**Issue by thommyhh** [FriendsOfTYPO3/content-blocks#153]
I've run into the scenario, where I define a collection with a foreign table (TCA) which is newly defined inside my content block. So I set the `table` property but not the `foreign_table` property. I want to use the relation (table) both for a field in `tt_content` and in  a property of a sub property, which is a collection of another table. Therefore I set `shareAcrossTables` and `shareAcrossFields`.

My `EditorInterface.yaml` looks like this:
```yaml
name: sitepackage/menu
prefixFields: false
fields:
   -  identifier: header
      useExistingField: true
      required: true
   -  &Dishes  
      identifier: dishes
      type: Collection
      labelField:
         - title
         - price
      table: tx_sitepackage_domain_model_dish
      fields:
         -  identifier: palette-title
            type: Palette
            fields:
            -  identifier: title
               type: Text
               required: true
            -  identifier: titleAdditionalInfo
               type: Text
         -  identifier: palette-price
            type: Palette
            fields:
               -  identifier: price
                  type: Number
                  format: decimal
                  required: true
               -  type: Linebreak
               -  identifier: pricePerPerson
                  type: Checkbox
                  renderType: checkboxToggle
               -  identifier: priceAdditionalInfo
                  type: Text
         -  identifier: description
            type: Textarea
            rows: 5
      appearance:
         collapseAll: true
         levelLinksPosition: both
      shareAcrossTables: true
      shareAcrossFields: true
   -  identifier: categories
      type: Collection
      labelField: title
      table: tx_sitepackage_domain_model_category
      fields:
         -  identifier: title
            type: Text
            required: true
         -  identifier: additionalInfo
            type: Textarea
         -  *Dishes
         -  identifier: columns
            type: Checkbox
            renderType: checkboxToggle
      appearance:
         collapseAll: true
         levelLinksPosition: both
   -  identifier: TYPO3/Appearance
      type: Basic
```

I ran into having a content element with UID 12 having some `dishes` and a category with UID 12 having some `dishes`. Despite the `shareAcrossTables` and `shareAcrossFields` the necessary `foreign_table_field` and `foreign_match_fields` were not set in the final TCA.
