### ISSUE TITLE
FieldType Color -> treeConfig.startingPoint is not working as aspected

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#167]
I have the following .yaml configuration:
```
name: treupo/json-tests
typeName: treupo_jsontests
title: 'JSON Tests'
description: 'Description for Content Element treupo/json-tests'
group: common
prefixFields: true
prefixType: full
fields:
  - identifier: category-test
    type: Category
    relationship: oneToOne
    treeConfig:
      startingPoints: '19'
```

It seems that the starting Point is not working. I expected that the categories starts from this uid and only the categories in the given pages are shown. But all categories are shown in the tree and the root category has "no title" and the uid which is given under the starting point. Very weird.
![Bildschirmfoto 2024-03-25 um 10 28 09](https://github.com/nhovratov/content-blocks/assets/107543296/abdb5321-243c-4f9d-8d2b-cc272f4c3806)

The category "Startseite" is under the root page with uid 1.
The category "content blocks" is under the page with uid 19.
The title "uid=19" from the screenshot appears when I hover over the first category which has the name "no title"

The generated TCA looks correct.

Or do I misunderstand this option?
