### ISSUE TITLE
ValuePicker for type EMail is not working

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#168]
I have the following configuration:

```
      - identifier: emailadvanced
        type: Email
        required: true
        default: 'example@test2.de'
        valuePicker:
          items:
            - example@test.de
            - second@test.de
```

The value picker is not working. Even if I use `- ['example mail', 'example@test.de']`.

In the code inside https://github.com/nhovratov/content-blocks/blob/1d651efaa981ee22adf5a60f2f48a95aa52a32b7/Classes/FieldType/EmailFieldType.php#L36 there is a value for $valuePicker and the TCA is generated accordingly but it seems, TYPO3 doesn't use a valuePicker for email fields. 

According to the Documentation, there is no valuePicker https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Email/Index.html
