### ISSUE TITLE
Error when saving irre records (collection) on page type

### ISSUE THREAD

**Issue by r3h6** [FriendsOfTYPO3/content-blocks#184]
Error: Attempt to insert record on page "Xyz" (n) where table "my_table_foo" is not allowed

Yaml: 
````
name: foo/recipe
typeName: 91
prefixFields: true
fields:
  - identifier: ingredients
    type: Collection
    labelField: ingredient
    fields:
      - identifier: ingredient
        type: Text
````

Expect: TCA security.ignorePageTypeRestriction in ctrl should be set to true

TYPO3 v12
content_blocks v0.7.3
