### ISSUE TITLE
[BUG] Array to string conversion in FlexForm

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#187]
Hi I have the following configuration (mostly copied from documentation https://docs.typo3.org/p/contentblocks/content-blocks/main/en-us/YamlReference/FieldTypes/FlexForm/Index.html#with-sheets)

```
name: treupo/flexformtest
table: tx_treupo_flexformtest
prefixFields: true
prefixType: vendor
security:
  ignorePageTypeRestriction: true
fields:
  - identifier: my_flexform
    type: FlexForm
    fields:
      - identifier: sheet1
        type: Sheet
        label: Sheet 1
        description: Description for Sheet 1
        linkTitle: Link title for Sheet 1
        fields:
          - identifier: header
            type: Text
          - identifier: check
            type: Checkbox
      - identifier: sheet2
        type: Sheet
        label: Sheet 2
        fields:
          - identifier: link
            type: Link
          - identifier: radio
            type: Radio
            default: 0
            items:
              - label: Option 1
                value: 0
              - label: Option2 2
                value: 1
```

When I edit the record type and then save it, I get the following error: 
`PHP Warning: Array to string conversion in /var/www/html/vendor/typo3/cms-backend/Classes/Utility/BackendUtility.php line 1495`

![Bildschirmfoto 2024-04-26 um 14 37 25](https://github.com/nhovratov/content-blocks/assets/107543296/264cee44-eefd-43d3-9afa-1c33426438dd)

The record itself is saved, I can see the changes when I open the record again.

TYPO3 12.4.14 and content_blocks main-branch from today. PHP 8.2.18, DDEV, composer mode
