### ISSUE TITLE
SQL type "varchar" for fieldtype "Select" could be too short for storing data

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#189]
Hi I have a fieldtype select, where I can select pages.

```
  - identifier: references
    type: Select
    renderType: selectTree
    size: 20
    foreign_table: 'pages'
    foreign_table_where: 'ORDER BY pages.uid'
    treeConfig:
      parentField: pid
      appearance:
        expandAll: true
        showHeader: true
```

In the database this field is created with a `varchar`:  https://github.com/nhovratov/content-blocks/blob/fd5dfbbe4437658b0686e7dd2eb9b55c96dc0d8f/Classes/FieldType/SelectFieldType.php#L199

In some cases this could lead into an error like this:
![Bildschirmfoto 2024-04-30 um 09 45 14](https://github.com/nhovratov/content-blocks/assets/107543296/fd598d12-45d7-48bb-bf54-94d11144e89d)

I checked a lot of pages inside the selectTree, untill it came to this error. There might be very few cases where it could come to this error but it could happen.

The field "pages" is stored with type "text" inside the database, maybe this could be the solution for type "Select" of CB.

**Comment by nhovratov** [comment]
This will be solved automatically with v13 as SQL columns will be generated based on TCA and the best fitting type will be chosen. For now, one must override the SQL in ext_tables.sql if varchar is not enough.

**Comment by PKuhlmay** [comment]
Okay I close this for now.

**Comment by PLACEBOBRO** [comment]
@nhovratov I upgraded to version 13, and now I'm encountering an issue where the database comparison truncates the field excessively. So if I want to execute the statement i get a "Error: Data too long for column 'header' at row 2".
<img width="781" alt="image" src="https://github.com/user-attachments/assets/9ada195d-c616-4537-9d71-a299a48f175d">

My content blocks configuration looks like this:
```
name: bt/slider
typeName: bt_slider
group: common
priority: 70
prefixFields: false
fields:
  -
    identifier: tx_basetemplate_slider_item
    type: Collection
    foreign_table: tx_basetemplate_slider_item
    foreign_field: tt_content
  -
    identifier: TYPO3/Appearance
    type: Basic
```
Do you have any suggestions how to solve this problem? I want to keep my DB compare clear and now there are very many statements after the upgrade which i can't apply.

**Comment by nhovratov** [comment]
@PLACEBOBRO I need to see the configuration for the record `tx_basetemplate_slider_item` to know what's going on. I have no idea, why it wants `header` to be `varchar(20)`. Is this a normal type `Text` field?

**Comment by PLACEBOBRO** [comment]
I believe I've identified the issue. Here is the configuration. The max attribute was not set when the field was originally created. I added it afterwards, but now Content-Blocks is attempting to truncate the values, even though there are still entries in the header field that exceed 20 characters.

```
name: bt/slider-item
table: tx_basetemplate_slider_item
prefixFields: false
fields:
  - identifier: header
    type: Text
    size: 50
    eval: trim
    max: 20
  - identifier: media
    type: File
    maxitems: 1
    allowed: jpg,jpeg,png,gif,bmp,pdf,svg,ai,mp3,wav,mp4,ogg,flac,opus,webm,youtube,vimeo
  - identifier: bodytext
    type: Textarea
    cols: 40
    rows: 3
    max: 120
  - identifier: bt/palette_button
    type: Basic
```
