### ISSUE TITLE
Extend page tca with contenblocks pagetype

### ISSUE THREAD

**Issue by graphicfox** [FriendsOfTYPO3/content-blocks#206]
Hello there,

I would like to create a bunch of new page types. Now I have everything tidy in my content blocks, but I also need to make changes on the default page type 1. Is there a way to use content blocks to extend/manipulate the TCA of the default page type 1?

Is there in general a good way to extend (for example) content types like "header" with content blocks instead of replacing them? At the moment, all default fields have to redefine.

```
name: custom/header
typeName: header
group: common
basics:
  - TYPO3/Appearance
prefixFields: true
prefixType: full
fields:
  -
    identifier: header
    label:
    useExistingField: true
  -
    identifier: palette_1
    type: Palette
    fields:
      -
        identifier: header_layout
        useExistingField: true
      -
        identifier: header_in_toc
        type: Checkbox
        label:
        description:
        renderType: checkboxToggle
        default: 1
 ```

Thanks :)
