### ISSUE TITLE
[SOLVED] missing required type on T3 V13.2 with CB Branch typo3-v13

### ISSUE THREAD

**Issue by APM-Thomas-Hempel** [FriendsOfTYPO3/content-blocks#215]
Ahoi,

I try to set up a V13 with Content Blocks and I found that the "typo3-v13" branch is supposed to be the one that will become the official cms/ package. So I used that one for my setup.

But I get an error when I use the built in Basics like `TYPO3/Header`. 

`The field "header" is missing the required "type" in Content Block "contents/textmedia".`

```
ddev typo3 cache:flush -g system && ddev typo3 extension:setup --extension=contents

                                                                                            
  [ InvalidArgumentException ]                                                              
  The field "header" is missing the required "type" in Content Block "contents/textmedia".  
                                                                                            

cache:flush [-g|--group [GROUP]]

Failed to run typo3 cache:flush -g system: exit status 255
```

My EditorInterface.yaml looks like this:

```
name: contents/textmedia
title: Textmedia
description: "Description for Content Element Textmedia"
group: common
prefixFields: true
prefixType: vendor
fields:

  - identifier: TYPO3/Header
    type: Basic

  - identifier: bodytext
    type: Textarea
    enableRichtext: true
    useExistingField: true

  - identifier: assets
    useExistingField: true
    type: File
    allowed: common-image-types
    minitems: 1
    maxitems: 1
```

I also have another issue, where it would not find my own Basics because they where not registered. Not sure if those things are related. The entire setup is working in a T3V12 with CB 0.6.4
