### ISSUE TITLE
Question to SQL error: "Unknown column in field list"

### ISSUE THREAD

**Issue by MAVEO-ps** [FriendsOfTYPO3/content-blocks#217]
Hello,
first of all, I'm new to Typo3 and just trying to work my way through the documents, but I hope this is the right place for my problem.

I have created a custom field in my EditorInterface.yaml as follows:
```
name: elem/header-default
title: Test
group: default
fields:
  - identifier: id
    type: Text
    label: LLL:EXT:site_package/Resources/Private/Language/locallang.xlf:fieldId.label
    description: LLL:EXT:site_package/Resources/Private/Language/locallang.xlf:fieldId.description
```

The field is also displayed in the back-end, but unfortunately I always get the error message when I try to save my inputs:
-**SQL error: "Unknown column 'elem_headerdefault_id' in 'field list'" (tt_content:NEW66a3731be4ddc077741414)** -

What exactly is the reason for this? Have I not installed my SitePackage correctly or is there a problem with ContentElements?

Many thanks for your help!
Pascal
