### ISSUE TITLE
Slug not generating correctly

### ISSUE THREAD

**Issue by simonmayr** [FriendsOfTYPO3/content-blocks#227]
This is my configuration where I'm using the field type "Slug"

```yaml
name: smprovider/newsitem
title: Slug Test
prefixFields: false
fields:
  - identifier: header
    useExistingField: true
    required: true

  - identifier: slug
    type: Slug
    eval: unique
    generatorOptions:
      fields:
        - header
```

When typing something into the header field, the following slug is generated: `default-13ec72ca2329698a42d44bb3f2eeb4b7`
Only after saving and refreshing, the slug is correctly generated.

https://github.com/user-attachments/assets/63792bff-8608-424e-b4d0-bef6643aa328

The expected behavior would be that the slug is generated automatically when typing into the header field.

**Comment by nhovratov** [comment]
I can confirm this behavior. Does not happen for simple records with slugs. Maybe because of TCA columnsOverrides.

**Comment by simonmayr** [comment]
It seems like the TCA is not generated correctly.
The configuration exists in `$GLOBALS['TCA']['tt_content']['columns']['test_new_slug']['config']` but the 'generatorOptions' are missing.

This Yaml:
```yaml
  - identifier: test_new_slug
    type: Slug
    generatorOptions:
      fields:
        - header
```

Generates this TCA:

![Bildschirmfoto 2024-08-19 um 13 25 24](https://github.com/user-attachments/assets/ed2c3cfc-e134-432c-9909-3ff0cb2d1621)

Therefor in `vendor/typo3/cms-backend/Classes/Controller/FormSlugAjaxController.php` line 84 the variable $fieldConfig is missing the generatorOptions and the slug generation returns 'default-xxxx'
