### ISSUE TITLE
Collection fields with "minitems" defined

### ISSUE THREAD

**Issue by MAVEO-ps** [FriendsOfTYPO3/content-blocks#228]
Hey, first of all, thank you very much for your help!

I have a problem with using collections as a field because I can't save a newly created page if the minitems value is set to 1 or higher, even if I create an element there correctly (see picture).

![Bildschirmfoto 2024-08-19 um 16 41 11](https://github.com/user-attachments/assets/4dca99bf-06d9-4e25-950e-54fd9f3722ec)

The collection still shows me an error despite the created element, which is why I cannot save it. If I set minitems to 0, the problem disappears.

This is my collection (the problem exists for every collection):
```
- identifier: header-slides
    type: Collection
    label: LLL:EXT:site_package/Resources/Private/Language/locallang.xlf:fieldSlides.label
    description: LLL:EXT:site_package/Resources/Private/Language/locallang.xlf:fieldSlides.description
    minitems: 1
    appearance:
      levelLinksPosition: bottom
    fields:
      - identifier: palette-appearance
        type: Palette
        label: LLL:EXT:site_package/Resources/Private/Language/locallang.xlf:paletteAppearance
        fields:
          - identifier: background-color
            type: Select
            renderType: selectSingle
            label: LLL:EXT:site_package/Resources/Private/Language/locallang.xlf:fieldBackgroundColor.label
            description: LLL:EXT:site_package/Resources/Private/Language/locallang.xlf:fieldBackgroundColor.description
            default: bg-white
            items:
              - label: LLL:EXT:site_package/Resources/Private/Language/locallang.xlf:fieldBackgroundColor.items.bg-white.label
                value: bg-white
              - label: LLL:EXT:site_package/Resources/Private/Language/locallang.xlf:fieldBackgroundColor.items.bg-light.label
                value: bg-light
              - label: LLL:EXT:site_package/Resources/Private/Language/locallang.xlf:fieldBackgroundColor.items.bg-dark.label
                value: bg-dark
```
                
Thank you for your help!

Kind regards
Pascal
