### ISSUE TITLE
treeConfig.startingPoints only works if admin with non-admin accounts it only shows the entry point category.

### ISSUE THREAD

**Issue by bzimm16** [FriendsOfTYPO3/content-blocks#257]
I have a yaml config like so;

```
  - identifier: categories
    useExistingField: true
    type: Category
    minitems: 1  
    maxitems: 5
    treeConfig:
      startingPoints: 5
    relationship: oneToOne
```

This works perfectlly  with admin accounts. However, if i use a non-admin account in the category filed only the entry point category is shown.  If i remove startingPoints from  the configuration all categories are shown. So it seems not to be an permission problem.
