### ISSUE TITLE
[DOCS] Additional examples for FIle -> cropVariants

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#259]
When I want to use the crop variants for a File, I always stumble over the correct usage of it.
I want to add a more specific example with some more variants so it will be easier to copy the variants and use it within any other content block.

https://docs.typo3.org/p/contentblocks/content-blocks/main/en-us/YamlReference/FieldTypes/File/Index.html#advanced-use-case

something like: (copied from my own sitepackage, this will not be the final code inside the documentation, its only an example)

```
name: example/image
typeName: example_image
prefixFields: true
prefixType: full
fields:
  - identifier: header
    useExistingField: true
  - identifier: image
    useExistingField: true
    allowed: ['jpg', 'jpeg', 'png', 'webp', 'tiff']
    cropVariants:
      desktop:
        title: Desktop
        allowedAspectRatios:
          subpages:
            title: Subpages
            value: 16/5
          homepage:
            title: Homepage
            value: 16/9
      smartphone:
        title: Smartphone
        allowedAspectRatios:
          subpages:
            title: Subpages
            value: 2/1
          homepage:
            title: Homepage
            value: 3/2

```
