### ISSUE TITLE
[DOCS] Add example for crop variant coverArea and focusArea

### ISSUE THREAD

**Issue by nhovratov** [FriendsOfTYPO3/content-blocks#280]

**Comment by PKuhlmay** [comment]
Example from Slack:
```
logocrop:
  title: 'Logo'
  focusArea:
    x: 0.3
    y: 0.3
    width: 0.4
    height: 0.4
  coverAreas:
    -
      x: 0.1
      y: 0.8
      width: 0.8
      height: 0.1
```

not tested 😅
