### ISSUE TITLE
[DOCS] Documentation on how to add icons to the Select Type

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#282]
Example:
```
  - identifier: icon
    type: Select
    renderType: selectSingle
    fieldWizard:
      selectIcons:
          disabled: false
    items:
      - value: facebook
        icon: social-media-facebook
      - value: instagram
        icon: social-media-instagram
      - value: linkedin
        icon: social-media-linkedin
      - value: youtube
        icon: social-media-youtube
```
