### ISSUE TITLE
Unknown type: link, render type: inputLink

### ISSUE THREAD

**Issue by linawolf** [FriendsOfTYPO3/content-blocks#284]
I am trying to migrate my first mask element.

This is my definition:
```
name: tx-mask/cardbox
typeName: mask_cardbox
prefixFields: false
fields:
  - identifier: header
    type: Text
  - identifier: header_link
    type: Link
  - identifier: image
    type: File
    allowed: common-image-types
  - identifier: bodytext
    type: Textarea
    enableRichtext: true
  - identifier: tx_mask_boxlayout
    type: Select
    renderType: selectSingle
    items:
      - label: 'Hauptfarbe'
        value: 0
      - label: 'Zweitfarbe'
        value: 300
```
When opening the record in the backend I get the following:
header_link
[header_link]
Unknown type: link, render type: inputLink

**Comment by linawolf** [comment]
I  tried switching to using the existing field, same effect:

```
name: tx-mask/cardbox
typeName: mask_cardbox
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
group: special
fields:
  - identifier: header
    useExistingField: true
  - identifier: header_link
    useExistingField: true
  - identifier: image
    useExistingField: true
  - identifier: bodytext
    useExistingField: true
  - identifier: tx_mask_boxlayout
    type: Select
    renderType: selectSingle
    items:
      - label: 'Hauptfarbe'
        value: 0
      - label: 'Zweitfarbe'
        value: 300
```
