### ISSUE TITLE
Unable to Render Images from FlexForm Field within Collection in TYPO3 Frontend

### ISSUE THREAD

**Issue by tgrigoryan234** [FriendsOfTYPO3/content-blocks#292]
I have an image field within a FlexForm field, but in the frontend, only the count of images is loaded, not the actual images. To address this, I need to write a custom Processor. This becomes more complex when the FlexForm field is part of a collection within a content element.
Example Content Element config.yaml
....
fields:
  -
    identifier: teasers
    type: Collection
    minitems: 1
    table: tx_teasers
    labelField: title
    appearance:
      collapseAll: true
      levelLinksPosition: bottom
    fields:
      - identifier: teaser
        type: FlexForm
        label: Teaser Settings

The FlexForm (teaser) inside this collection includes an image field. How can I retrieve and display the actual image in the frontend?
There are currently no hooks or  signals or options in the Data Decoration process that allow adding a field to Content Block data. In the past, this was possible using the offsetSet function. I don’t understand why it was removed.

**Comment by nhovratov** [comment]
Which version are you on? TYPO3 v13 / v1 or TYPO3 v12 / 0.x?

**Comment by nhovratov** [comment]
In v13 FlexForm relations should be resolved as well. Could you please show me your complete yaml snippet of the FlexForm field?

**Comment by nhovratov** [comment]
Just tested it with this configuration and it works:

```
name: example/card-group
fields:
  - identifier: header
    useExistingField: true
  - identifier: settings
    type: FlexForm
    fields:
      - identifier: image
        type: File
  ```
  
  
![Screenshot 2024-11-14 at 10-10-21 Home](https://github.com/user-attachments/assets/d93473b3-efaf-46ca-b91f-93a5dbe57f0a)
