### ISSUE TITLE
Link fields within FlexForm are not resolved

### ISSUE THREAD

**Issue by websi** [FriendsOfTYPO3/content-blocks#296]
**Describe the bug**
The link fields within FlexForm fields not resolved. The value is always "null" in fluid

**To Reproduce**

Create an new content element.

```yaml
name: dkd-customer/quote
typeName: dkdcustomer_quote
group: default
prefixFields: true
prefixType: full
basics:
  - TYPO3/Appearance
fields:
  - identifier: TYPO3/Header
    type: Basic
  - identifier: bodytext
    type: Textarea
    required: true
    enableRichtext: true
    useExistingField: true
  - identifier: pi_flexform
    type: FlexForm
    useExistingField: true
    fields:
      - identifier: author
        type: Text
      - identifier: url
        type: Link
        autocomplete: true
        allowedTypes:
          - page
          - url
```

Output the content within `frontend.html`

```html
<f:section name="Main">
	<f:debug title="All">{_all}</f:debug>
	<f:debug title="URL Content Blocks 'data.pi_flexform.url'">{data.pi_flexform.url}</f:debug>
	<f:debug title="URL Content Blocks 'data.pi_flexform.url.url'">{data.pi_flexform.url.url}</f:debug>
<blockquote cite="{f:if(condition: '{data.pi_flexform.url.url}', then: '{f:uri.typolink(parameter: data.pi_flexform.url.url)}')}">
	<f:format.html>{data.bodytext}</f:format.html>
	<f:if condition="{flexFormData.author}"><footer><cite>{flexFormData.author}</cite></footer></f:if>
</blockquote>
</f:section>
```

**Expected behavior**
The link field should be resolved correctly

**Screenshots**

![image](https://github.com/user-attachments/assets/01d2c964-a451-4f3d-9a8f-1a672e460cc8)

The flex-form data provided via 

```
tt_content.dkdcustomer_quote {
  dataProcessing {
    # RecordPropertyClosure are neve resolved
    5 = flex-form
  }
}
```

**TYPO3 Version** - 13.4.1

**Content Blocks Version:** - 1.0.4

**Additional context**
