### ISSUE TITLE
MariaDB Exception creating record-type

### ISSUE THREAD

**Issue by fe-mohmand** [FriendsOfTYPO3/content-blocks#30]
Steps to reproduce:

- create new record-type with make:content-block
- name should be **test-slides**
- run "Analyse Databse Structure" and then "Apply selected changes" in TYPO3 Backend

This will lead to 
`Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-slides (`uid` INT UNSIGNED AUTO_INCREMENT NOT NULL, `pid` INT `

Reason is the generated table name "**tx_vendorname_domain_model_test-slides**" in EditorInterface.yaml
It should be "**tx_vendorname_domain_model_test_slides**"

**Comment by nhovratov** [comment]
Thanks for reporting the issue! Seems like TYPO3 doesn't escape these table names. Will have a look at this. The generated table name should be separated by underscores though, you are right.

**Comment by PKuhlmay** [comment]
@nhovratov Is this still solved? 
I get an error with the following yaml:

```
name: foo/content-list
group: treupo
prefixFields: true
prefixType: full
fields:
  - identifier: header
    useExistingField: true
  - identifier: test-collection
    type: Collection
    fields:
      - identifier: media
        type: File
        allowed: png, jpg, jpeg, webp, mp4, mpeg
        minitems: 1
        maxitems: 1
```

The Database Analyzer now wants to create this table: `CREATE TABLE foo_contentlist_test-collection` which results into an error. Changing the indentifier to test_collection works because of the underscore (_) instead of the dash (-)

TYPO3 12.4.11
CB 0.6.1
Database: MariaDB 10.4 (ddev)
