### ISSUE TITLE
Error: You have an error in your SQL syntax;

### ISSUE THREAD

**Issue by linawolf** [FriendsOfTYPO3/content-blocks#305]
**Describe the bug**
On doing database compare after creating my block I get the following error:

![image](https://github.com/user-attachments/assets/a71fbaa0-f944-470c-a01a-efcf742c5e92)

**To Reproduce**
```
name: t3docs/carousel
typeName: t3docs_carousel
group: default
prefixFields: true
prefixType: full
fields:
  - identifier: carousel-items
    type: Collection
    foreign_field: parentid
    fields:
      - identifier: header
        type: Text
      - identifier: description
        type: Textarea
        enableRichtext: true
      - identifier: image
        type: File

```

**Expected behavior**
If the special sign `-` is not possible it should be forbidden or transformed.

**TYPO3 Version**
13.4.1

**Content Blocks Version:**
friendsoftypo3/content-blocks (1.0.4)

**Additional context**
Using `identifier: carousel_items` works
