### ISSUE TITLE
Collection with foreign table ist not working

### ISSUE THREAD

**Issue by fe-mohmand** [FriendsOfTYPO3/content-blocks#31]
Regarding the advanced example for collection in the [documentation ](https://docs.typo3.org/c/contentblocks/content-blocks/main/en-us/IntegratorManual/YamlReference/FieldTypes/Collection/Index.html)

```
# This custom table needs to be defined in a separate Content Block
name: example/slide
table: my_slide
aggregateRoot: false
fields:
  - identifier: image
    type: File

name: example/collection
group: common
fields:
  - identifier: slides
    type: Collection
    foreign_table: my_slide
```

This is not working. You will get an exception in backend page module and in frontend after creating the content element:

(1/1) #1628925803 OutOfBoundsException
The table "example_collection_slides" does not exist.

You can create the example_collection in the list module and its irrre elements are stored correct in my_slide table.
Maybe the configuration in EditorInterface.yaml is wrong
