### ISSUE TITLE
foreign_field must not be set if MM is used

### ISSUE THREAD

**Issue by linawolf** [FriendsOfTYPO3/content-blocks#310]
**Describe the bug**
The media items are always empty

**To Reproduce**
```
name: my/slider
typeName: myslider_carousel
group: default
prefixFields: false
fields:
  -
    identifier: header
    useExistingField: true
    label: 'Internal title (not displayed)'
  -
    identifier: tx_myslider_slidercontent
    type: Collection
    labelField: title
    MM: tx_content_myslider_slidercontent_mm
    fields:
      - identifier: media
        type: File
      - identifier: duration
        type: Number
        default: 0
```

**Expected behavior**
Media can be used

**Screenshots**
![image](https://github.com/user-attachments/assets/86e58860-05c0-489c-a79e-ad12e5897371)

![image](https://github.com/user-attachments/assets/48df4d44-b049-4f00-99fd-f9795430710a)

**TYPO3 Version**
13.4.1

**Content Blocks Version:**
latest composer

**Additional context**
Migrating an existing slider extension that already uses MM tables
