### ISSUE TITLE
Flex Form Field is inaccessible after the 13.4.2 update

### ISSUE THREAD

**Issue by tgrigoryan234** [FriendsOfTYPO3/content-blocks#318]
**Describe the bug**
After the minor update, the Flex Form fields are no longer accessible. It is empty.

**To Reproduce**
```
 fields:
  - identifier: my_flexform
    type: FlexForm
    fields:
      - type: Sheet
        identifier: sheet1
        label: Sheet 1
        fields:
          - identifier: section1
            type: Section
            label: Section 1
            container:
              - identifier: container1
                label: Container 1
                fields:
                  - identifier: container_field
                    type: Text
              - identifier: container2
                label: Container 2
                fields:
                  - identifier: container_field2
                    type: Textarea
``` 

**Screenshots**
![Bildschirmfoto 2024-12-10 um 14 54 22](https://github.com/user-attachments/assets/50f37b58-d9f7-4cad-b300-353d106f422d)
![Bildschirmfoto 2024-12-10 um 14 54 38](https://github.com/user-attachments/assets/82b951f4-cd6d-4880-b366-54c72c67d473)

**TYPO3 Version**
13.4.2
