### ISSUE TITLE
[FEATURE] Basics overrides

### ISSUE THREAD

**Issue by TheNaderio** [FriendsOfTYPO3/content-blocks#338]
**Is your feature request related to a problem? Please describe.**
We add some default fields within a palette from a Basic. Some elements needs a custom default value for some fields, e.g. `background_type=1`

**Describe the solution you'd like**
Something like:
```yaml
name: vender/block
typeName: block
group: default
prefixFields: false
basics:
  - Tab/Appearance.   // <<----- Here the field 'background_type' is added, with default=0
fields:
  [...]

  - identifier: background_type
    columnsOverrides:
        config:
            default: 1
```
or on content-block level:

```yaml
name: vender/block
typeName: block
group: default
prefixFields: false
basics:
  - Tab/Appearance.   // <<----- Here the field 'background_type' is added, with default=0
columnsOverrides:
    config:
        default: 1
fields:
  [...]
```

**Describe alternatives you've considered**
For now, we add the content-block to `$GLOBALS['TCA']['tt_content']['types']['<contentblock-name>']` and add the corresponding field including the columnsOverride.
That works well, but i'd love to set this up in the content-block's config.yaml.

**Additional context**
I think the description explains it well. 
Otherwise i'm open to provide more information when needed :)

**Comment by nhovratov** [comment]
Reasonable request. I will consider it as a feature for the next release. It will probably be more like a mix of both examples (I want to avoid the term `columnsOverrides` in Content Blocks, as it is hard to explain. Maybe something like this:

```yaml
name: vender/block
typeName: block
group: default
prefixFields: false
basics:
  - Tab/Appearance.   // <<----- Here the field 'background_type' is added, with default=0
basicsOverrides:
  - identifier: background_type
    default: 1
fields:
  [...]
```
