### ISSUE TITLE
[FEATURE] Override/extend existing content elements/records

### ISSUE THREAD

**Issue by thommyhh** [FriendsOfTYPO3/content-blocks#34]
It would be nice to be able to extend existing records (pages, tt_content, ...) with new fields using the YAML syntax of the `content_blocks` extension.

I would suggest a folder structure like `ContentBlocks/Overrides/{ContentElements,PageTypes,RecordTypes}` similar to the `Configuration/TCA/Overrides` folder used by the TYPO3 Core.

If the table to be overridden does not exist - in case of `RecordTypes` - an exception should be thrown to make it clear, that there is an error.

The YAML syntax could look like this:

```yaml
name: t3core/1 # this should override doktype = 1; t3core as vendor prefix indicates, that this is a core type, which does not have a prefix in the TCA
fields:
   # Adds new field after the field `seo_title`
   -  identifier: my_special_field
      type: Textarea
      enableRichtext: true
      after: seo_title # Can be either a field or `palette:{name_of_palette}`
      linebreak: 'before' # Could be `before`, `after` or `both` to insert additional line break before and/or after the field we add
   # Adds new field before the field `description`
   -  identifier: my_other_field
      type: Link
      before: description # Can be either a field or `palette:{name_of_palette}`
      linebreak: 'after' # Could be `before`, `after` or `both` to insert additional line break before and/or after the field we add
   # Adds new tab at the end
   -  identifier: settings_tab
      type: Tab
      fields:
         -  identifier: header_menu_pages
            type: Relation
            allowed: pages
      # It is also possible to add a tab after field or palette like with a single field. The new tab is inserted after the tab, the given field or palette is located in
      after: no_follow # Field identifier or `palette:<name-of-palette>`
```

Another feature could be to make it possible to override existing fields, e.g. to assign a new label, change the configuration or move the field to another tab or palette. However, the type must not change, to avoid issues the underlying database field.
```yaml
name: t3core/1 # this should override doktype = 1; t3core as vendor prefix indicates, that this is a core type, which does not have a prefix in the TCA
fields:
   # This would throw an exception "You must not change the type of an existing field. Do not use `useExistingField` and `type` together."
   -  identifier: keywords
      useExistingField: true
      type: Textarea
      after: description 
      linebreak: 'before'
   # Move the field after the `description` field in the `SEO` tab
   -  identifier: abstract
      useExistingField: true
      after: description 
      linebreak: 'before'
```
