### ISSUE TITLE
Missing $LANG variable in Collection using tt_content

### ISSUE THREAD

**Issue by Danny-HPH** [FriendsOfTYPO3/content-blocks#343]
**Describe the bug**
If a Collection is using tt_content as a foreign_field and for example a typo3 form is added in this. The $LANG variable is not available in this scope and we get an Exception:
`PHP Warning: Undefined global variable $LANG in /html/typo3-composer/vendor/typo3/cms-form/Classes/Domain/Configuration/FlexformConfiguration/Processors/FinisherOptionGenerator.php line 96`

**To Reproduce**
1. Create an Element that uses a Collection with foreign_table: tt_content
2. Insert a Typo3 Form element into it
3. Open frontend and get the error

**Expected behavior**
The Form element gets the $LANG variable in this scope.

**Screenshots**
![Image](https://github.com/user-attachments/assets/b882ed18-d050-4418-a083-915d40d14647)

**TYPO3 Version**
13.4.5

**Content Blocks Version:**
1.1.6

**Comment by nhovratov** [comment]
Hey, I don't think it's a good idea to put a form plugin into a Collection. Have you considered a container?
Anyway, this is not a Content Blocks issue. Could you please forward this issue to TYPO3 forge?

**Comment by Danny-HPH** [comment]
ok thanks, i added a forge issue.

**Comment by nhovratov** [comment]
Related issue on forge: https://forge.typo3.org/issues/106158

**Comment by nhovratov** [comment]
Could you please provide the YAML configuration so we can quickly reproduce it?

**Comment by Danny-HPH** [comment]
Sure:

```
name: pxproject/specialbox
group: pxproject_content_elements
prefixFields: false
basics:
    - TYPO3/Appearance
fields:
  - identifier: image
    type: File
    maxitems: 1
    minitems: 1
    allowed: common-image-types
  - identifier: content
    type: Collection
    minitems: 1
    required: 1
    foreign_table: tt_content

```
