### ISSUE TITLE
Field Type "Relation" works only with "page" table

### ISSUE THREAD

**Issue by glucka** [FriendsOfTYPO3/content-blocks#345]
With following config i can select only pages in backend

```
fields:
  - identifier: record
    type: Relation
    allowed: 'tt_content'
    suggestOptions:
      default:
        additionalSearchFields: 'uid, bodytext'
```
