### ISSUE TITLE
Render nested Content Elements in the frontend over data._grids not working

### ISSUE THREAD

**Issue by glucka** [FriendsOfTYPO3/content-blocks#346]
![Image](https://github.com/user-attachments/assets/364b3f06-280b-4a40-b11b-7cfe321cb8cd)

Config:
```
  - identifier: accordion_item
    type: Collection
    labelField: title
    minitems: 1
    fields:
      - identifier: title
        type: Text
      - identifier: subtitle
        type: Text
      - identifier: records
        type: Collection
        labelField: text
        minitems: 1
        foreign_table: tt_content
        overrideChildTca:
          columns:
            CType:
              config:
                default: ag_text
```
Frontend:
```
<f:for each="{data._grids.accordion_item}" as="records">
        <f:debug>{records}</f:debug>
        <f:for each="{records}" as="record" iteration="i">
            <f:format.raw>{record.content}</f:format.raw>
        </f:for>
    </f:for>
```
Latest Typo3 (13.4.5), latest ContentBlocks (1.1.6)
