### ISSUE TITLE
storagePid for type Relation

### ISSUE THREAD

**Issue by Make66** [FriendsOfTYPO3/content-blocks#347]
To prevent the user to search through the tree to find the sysfolder with the related records, we could give an optional default for the pid or even force it.
I am suggesting 2 options:
pidSuggested: number (point the record browser to this sysfolder first)
pidForced: number (get the reords only from there)

**Comment by nhovratov** [comment]
This feature already exists: https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Group/Index.html#confval-group-elementbrowserentrypoints

It's called `elementBrowserEntryPoints`

**Comment by Make66** [comment]
So next to config.yaml we configure some overwrite/pages.php? Or can this option be used inside the config.yaml (guess not).

**Comment by nhovratov** [comment]
Just convert it to YAML syntax:

```yaml
- identifier: my_identifier
  type: Relation
  allowed: tt_content
  elementBrowserEntryPoints:
    _default: 123
```
