### ISSUE TITLE
Add custom typoscript to Content-Block

### ISSUE THREAD

**Issue by subjacked** [FriendsOfTYPO3/content-blocks#35]
Supply a way to enrich content-blocks with custom typoscript Rendering, e.g. DataProcessors like Menu. This should happen in the folder of the specific content-block to maintain the easyness of copying the blocks.

**Comment by subjacked** [comment]
My solution for now looks like this

![image](https://github.com/nhovratov/content-blocks/assets/2064769/ccd24946-a7f0-45a1-b634-ac9e09c06ee6)
![image](https://github.com/nhovratov/content-blocks/assets/2064769/6781caa1-c177-4956-a339-5352b32079e8)

**Comment by peterkraume** [comment]
I like the idea, but I would prefer a solution where a specific TypoScript file within a content block is included automatically if it is present. From there I could then include more files if necessary.

**Comment by krausandre** [comment]
Despite I understand the wish and the need to have this, I don't think this is a good idea, because we want to keep content blocks as easy as possible. And therefore there are results in the concept saying no PHP, no TypoScript and so on.

**Comment by jonaseberle** [comment]
Maybe not in the form of a generic TypoScript but rather just the possibility to define (and configure) additional DataProcessors?

**Comment by krausandre** [comment]
@jonaseberle do you mean something like adding DataProcessors via the config yaml?

**Comment by schliesser** [comment]
Could be a nice way. Here a current example with conditions in the dataProcessing configuration

My typoscript
```typoscript
# Menu Cards (selected or subpages of selected)
tt_content.vendor_menucards {
  dataProcessing {
    200 = menu
    200 {
      # Show selected pages
      if.isFalse.field = vendor_show_subpages
      special = list
      special.value.field = pages
      dataProcessing {
        10 = record-transformation
      }
    }
    300 = menu
    300 {
      # Show subpages of selected pages
      if.isTrue.field = vendor_show_subpages
      special = directory
      special.value.field = pages
      dataProcessing {
        10 = record-transformation
      }
    }
  }
}
```

Idea for definition in `config.yaml`
```yaml
name: vendor/menu-cards
typeName: vendor_menucards
group: menu
prefixFields: true
prefixType: vendor
fields:
  - identifier: TYPO3/Header
    type: Basic
  - identifier: pages
    useExistingField: true
    minitems: 1
  - identifier: show_subpages
    type: Checkbox
    renderType: checkboxToggle
basics:
  - TYPO3/Appearance
  - TYPO3/Links
dataProcessing:
  - type: menu
    config:
      if.isFalse.field: vendor_show_subpages
      special: list
      special.value.field: pages
      dataProcessing:
        - type: record-transformation
  - type: menu
    config:
      if.isTrue.field: vendor_show_subpages
      special: list
      special.value.field: pages
      dataProcessing:
        - type: record-transformation
```
