### ISSUE TITLE
Strange behaviour if same field is used multiple times

### ISSUE THREAD

**Issue by georgringer** [FriendsOfTYPO3/content-blocks#350]
If you got 2 blocks using the same field but with a different configuration, there is no hint why a configuration is not used.

Example

got block `cta` with
```yaml
  -
    identifier: link
    type: Text
```

and `keyvisual` with
```yaml
  -
    identifier: link
    type: Link
```

now also the keyvisual didn't get the type link but stayed as plain input field.

I see there 2 options:
- Use the tca override to set the type to the proper configuration
- provide a warning

it is impossible for an integrator to find out the issue. I also wondering about the loading order as I thought that keyvisual wins over cta but that is a different thing
