### ISSUE TITLE
Incorrect sys_language_uid assignment in sys_file_reference (RecordTypes)

### ISSUE THREAD

**Issue by robinson2** [FriendsOfTYPO3/content-blocks#355]
**TYPO3 Version**
13.4.5

**Issue**
When using RecordTypes , setting `extendedPalette: false` for a File field causes sys_language_uid in sys_file_reference to always be 0, even if the parent record has a different language.

**Minimal Example (config.yaml)**
```
name: r2/icons
table: tx_r2_icons
prefixFields: false
labelField: title
sortField: title
fields:
  -
    identifier: title
    type: Text
    label: Title
    required: true
  -
    identifier: image
    type: File
    extendedPalette: false
    allowed: common-image-types
    maxitems: 1
    label: Bild (SVG)
```

**Expected Behavior**
sys_language_uid in sys_file_reference should inherit the language from the parent tx_r2_icons record.

**Actual Behavior**
sys_language_uid is always 0, leading to incorrect language relations.

**Workaround**
Removing extendedPalette: false fixes the issue, but this should not be necessary.
