### ISSUE TITLE
Page View Not Accessible with Content Block Elements Containing Links to Protected Pages

### ISSUE THREAD

**Issue by stephangrass** [FriendsOfTYPO3/content-blocks#359]
I have created a simple content block element:

```
name: vendor/text
typeName: vendor_text
group: default
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
fields:
  - identifier: TYPO3/Header
    type: Basic
  - identifier: bodytext
    useExistingField: true
    enableRichtext: true
```

When I create a link to an access-protected page in the bodytext field, the page view can no longer be accessed. The browser (Firefox, Chrome) keeps loading indefinitely, and the error NS_BINDING_ABORTED appears in the network analysis.

With normal standard page elements like Text-Media, this is not an issue.
