### ISSUE TITLE
IRRE FAL field visibility toggle not responding

### ISSUE THREAD

**Issue by AnuBhuvanendranNair** [FriendsOfTYPO3/content-blocks#367]
While adding media/image/fal fields in collections, this will render the field in the backend which does not respond to enable/disable toggle.

To reproduce,
1. create a content with an image field as a collection in it.

```
 -
    identifier: contact_set
    type: Collection
    label: Contact
    maxitems: 20
    table: tx_sitepackage_contact_section
    labelField: name
    appearance:
      collapseAll: true
    fields:
      -
        identifier: profile_image
        label: Profil Bild
        type: File
        extendedPalette: true
        minitems: 0
        maxitems: 1
        allowed: common-image-types
```
2. add definition in ext_tables.sql

```
##
# Table structure for table 'tx_sitepackage_contact_section'
#
CREATE TABLE tx_sitepackage_contact_section
(
    profile_image int(11) unsigned NOT NULL default '0',
    directions varchar(255) DEFAULT '' NULL,
    foreign_table_parent_uid int(11) unsigned NOT NULL default '0',
);
```
3. add element in a page and hide the image element within.
4. while saving it is visible that the image field isn't hidden but is visible.

Expected behaviour is that it should be possible to toggle an element's visibility even if it is inside a collection.

**Environment**
content_blocks - 1.1.9
TYPO3 - 13.4.8
