### ISSUE TITLE
Backend preview (grid) for nested content elements (collection): hidden records are not shown

### ISSUE THREAD

**Issue by kraemer-igroup** [FriendsOfTYPO3/content-blocks#369]
**TYPO3 Version:** 13.4.8 + Patch https://review.typo3.org/c/Packages/TYPO3.CMS/+/88917
**PHP Version:** 8.2
**Content Blocks Version:** 1.1.9

`config.yaml`:
```yaml
name: igroup/facts
group: special
prefixType: vendor
fields:
  - identifier: facts_item
    type: Collection
    labelField: description
    appearance:
      collapseAll: true
      levelLinksPosition: bottom
    fields:
      - identifier: headline
        type: Text
      - identifier: description
        type: Textarea
        rows: 2
```

`templates/backend-preview.html`:
```html
<f:render partial="PageLayout/Grid" arguments="{data: data, identifier: 'facts_item'}"/>
```

Hidden records are not shown in page module:
![Image](https://github.com/user-attachments/assets/27c077a7-157d-400a-81dc-ee732fb5295f)

![Image](https://github.com/user-attachments/assets/041caa56-4c9e-435b-bd81-f55dc2b3edd4)

They are also missing inside the `{data}` array.

Thanks for having a look!
