### ISSUE TITLE
Check for Broken Extensions shows "Loading ext_tables.php of extension "xyz" failed"

### ISSUE THREAD

**Issue by b3nkai** [FriendsOfTYPO3/content-blocks#377]
**Describe the bug**

In backend "Upgrade" module, when checking for broken extension, this error can occurs on our custom extension in some cases:

Check for Broken Extensions shows "Loading ext_tables.php of extension "xyz" failed"

**To Reproduce**

Create au custom extension, "site" for example

Create a custom element with this configuration:

```
name: site/header
prefixFields: false
basics:
  - TYPO3/Appearance
fields:
  -
    type: Text
    identifier: header
    useExistingField: true
```

In ext_tables.php, make an instance of PageDoktypeRegistry:

```
<?php

declare(strict_types=1);

use TYPO3\CMS\Core\DataHandling\PageDoktypeRegistry;
use TYPO3\CMS\Core\Utility\GeneralUtility;

defined('TYPO3') || die();

(static function () {
    GeneralUtility::makeInstance(PageDoktypeRegistry::class);
})();
```

Go to backend module "Upgrade" and check for broken extension. this error will be displayed:

Check for Broken Extensions shows "Loading ext_tables.php of extension "site" failed"

**Expected behavior**

No error.

**Cause**

When using xdebug, you can find the exception which cause this error:

```
message = "The field "layout" is missing the required "type" in Content Block "site/header"." 
file = "/var/www/html/vendor/friendsoftypo3/content-blocks/Classes/Definition/Factory/ContentBlockCompiler.php" 
line = 967
```

This error is due to basic declaration of some fields, like "layout":

```
# To be used within ContentElements
identifier: TYPO3/Appearance
fields:
  -
    identifier: appearance_tab
    type: Tab
    label: LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.appearance
  -
    identifier: frames_palette
    type: Palette
    label: LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.frames
    fields:
      -
        identifier: layout
        useExistingField: true
      -
        identifier: frame_class
        useExistingField: true
      -
        identifier: space_before_class
        useExistingField: true
      -
        identifier: space_after_class
        useExistingField: true
```

The basic definition does not define the "type" configuraiton which is mandatory.

**Versions**

TYPO3 Version: 13.4.9
Content-block Version: 1.1.11

**Related issues**

https://forge.typo3.org/issues/104737
https://github.com/FriendsOfTYPO3/content-blocks/issues/338
