### ISSUE TITLE
Missing required type when using existing field

### ISSUE THREAD

**Issue by lst-team** [FriendsOfTYPO3/content-blocks#389]
**Describe the bug**
When executing 'Check TCA in ext_tables.php' I get an InvalidArgumentException.
But in all other places it seems fine. I can edit and save the content element without errors.

**To Reproduce**
1. Go to 'Admin Tools' -> 'Upgrade'
2. Click on 'Check TCA in ext_tables.php'
3. See error

**Expected behavior**
The type should be taken over from the existing field and there should be no error thrown.

**Configuration**
```yaml
name: lst/iframe
group: dce
prefixFields: true
basics:
  - TYPO3/Appearance
fields:
  -
    identifier: header
    useExistingField: true
  -
    identifier: url
    type: Text
    eval: trim
    required: true
prefixType: vendor
vendorPrefix: tx_sitelwo
```

**Screenshots**
<img width="878" alt="Image" src="https://github.com/user-attachments/assets/c3a83b16-80c6-4e26-b777-5ba9591dc249" />

**TYPO3 Version:** 13.4.13
**Content Blocks Version:** 1.3.4 (Composer)
