### ISSUE TITLE
type: Category, relationship: oneToMany should store as csv

### ISSUE THREAD

**Issue by glucka** [FriendsOfTYPO3/content-blocks#392]
Up to Typo3 v12 if i override the categories field:

```
$GLOBALS['TCA']['pages']['columns']['categories'] = [
            'l10n_mode' => 'exclude',
            'config' => [
                'type' => 'category',
                'relationship' => 'oneToMany'
            ],
        ];
```

Store every category ID comma separated in DB.

But with Typo3 v13 and latest Content Blocks PageType config.yaml:

```
name: ag/default
title: Default
typeName: 1
fields:
  - identifier: categories
    useExistingField: true
    type: Category
    relationship: oneToMany
```

I see only the nr of the categories (like with ManyToMany)

**Comment by nhovratov** [comment]
In your example you change the relation **globally** for the field. This does not work for Content Blocks. Please create a new category field for that.

if you really need it to be this field, you can still override it with TCA like in the example and just reuse it in Content Blocks:

```yaml
fields:
  - identifier: categories
    useExistingField: true
```
