### ISSUE TITLE
Same type overrides for multiple content blocks

### ISSUE THREAD

**Issue by Mainbird** [FriendsOfTYPO3/content-blocks#404]
Hi @nhovratov,

if I am using something like this: https://docs.typo3.org/p/friendsoftypo3/content-blocks/main/en-us/API/TypeOverrides/Index.html#example-3-override-file-types

and want to override the same type of the image field for another content block then it seems that the last type override affects all other references. So I can't do it for multiple content blocks or do I miss something?

I want to achieve something like this:

- content-block-a
  - image
     - alternative
     -  crop
- content-block-b
  - image
     - alternative

but the second override of content-block-b affects the type override of content-block-a which I want to avoid.
We currently do something similar with TCA overrides, which work as expected, but I thought maybe I could migrate this to the type overrides.

**Comment by nhovratov** [comment]
@Mainbird Did you use different identifiers for the Palettes? If not, then the last Palette definition will override the first.
So:

```yaml

  - identifier: file_override
    type: File
    overrideType:
      image:
        - identifier: image_overlay_palette
          type: Palette
          label: 'LLL:EXT:core/Resources/Private/Language/locallang_tca.xlf:sys_file_reference.imageoverlayPalette'
          fields:
```
```yaml

  - identifier: file_override
    type: File
    overrideType:
      image:
        - identifier: image_overlay_palette_2
          type: Palette
          label: 'LLL:EXT:core/Resources/Private/Language/locallang_tca.xlf:sys_file_reference.imageoverlayPalette'
          fields:
```
