### ISSUE TITLE
PageType -> image -> enableImageManipulation has no effect

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#45]
I have a custom page type which has an image for which I wanted to disable the image manipulation.
I first set it to true, this worked. Then I set it to false, cleared all the caches and reloaded the page. I still have the possibility to manipulate the image:

<img width="1193" alt="Bildschirmfoto 2023-11-10 um 21 18 56" src="https://github.com/nhovratov/content-blocks/assets/107543296/757107d5-6b27-4138-acb9-5bc1aa10e11c">

My configuration is this:
```
name: treupo/testing
typeName: 3987
prefixFields: true
fields:
    -   identifier: image
        type: File
        enableImageManipulation: false
        maxitems: 5
        minitems: 3
        allowed: common-image-types
```

It doesn't care which configuration I use, neither true nor false is working. Even if I remove the line for enableImageManipulation doesn't work. According to the documentation at https://docs.typo3.org/p/contentblocks/content-blocks/main/en-us/IntegratorManual/YamlReference/FieldTypes/File/Index.html#confval-enableImageManipulation the default value is `false`

I also created a whole new page type with an image without the line `enableImageManipulation`, it still was there.
