### ISSUE TITLE
Multiple fields of type Collection in single Content Block not possible

### ISSUE THREAD

**Issue by nilkra** [FriendsOfTYPO3/content-blocks#54]
If I am creating multiple collection fields in a single Content Block, i only get the data from the first collection field. The remaining collection fields only return an integer value containing the count of the items i put in and not an array with the data.

// EditorInterface.yaml:

![editorInterface](https://github.com/nhovratov/content-blocks/assets/77601065/e6293e97-062c-4375-bd2f-dbcf58b04bab)
  
// Output:

![output](https://github.com/nhovratov/content-blocks/assets/77601065/6ef14e06-2b7a-4cf1-b64d-216a0945b8bd)

**Comment by PKuhlmay** [comment]
Hi @NzudemK Could you also provide the yaml as Code, not as a screenshot? This makes debugging much more easy.

**Comment by nilkra** [comment]
Hello @PKuhlmay.
Of course, this is the code version:
```
name: project/footer
group: common
prefixFields: true
fields:
  - identifier: title
    label: Titel
    type: Text
  - identifier: description
    label: Beschreibung
    type: Textarea
    enableRichtext: true
  - identifier: footerIcon
    label: Icons mit Links für Footer
    type: Collection
    labelField: link
    minitems: 1
    fields:
      - identifier: icon
        label: Icon
        type: File
      - identifier: link
        label: Link
        type: Link
  - identifier: footerLink
    label: Links für Footer
    type: Collection
    labelField: linkText
    minitems: 1
    fields:
      - identifier: linkText
        label: Text für Link
        type: Text
      - identifier: link
        label: Link
        type: Link
  - identifier: footerBottomLink
    label: Links für unteren Footer Bereich
    type: Collection
    labelField: linkText
    minitems: 1
    fields:
      - identifier: linkText
        label: Text für Link
        type: Text
      - identifier: link
        label: Link
        type: Link
```
