### ISSUE TITLE
Allow to use "." within FlexForm field Names

### ISSUE THREAD

**Issue by DanielSiepmann** [FriendsOfTYPO3/content-blocks#67]
This is necessary in order to keep compatible with Extbase Plugins.
Extbase has a convention to add values stored within settings.<name> fields within pi_flexform of tt_content to the $this->settings array of plugins.

E.g. the following would work normally:

```yaml
name: 'codappix/list'
group: 'special'
fields:
     -
         identifier: 'pi_flexform'
         useExistingField: true
         type: 'FlexForm'
         fields:
             -
                 identifier: 'settings.record_types'
                 type: 'Select'
```

But does not yet work with content blocks as they strip off the dot within the field name.
