### ISSUE TITLE
 (1/1) TypeError  TYPO3\CMS\ContentBlocks\DataProcessing\ContentBlockDataResolver::transformSelectSingleRelation(): Return value must be of type TYPO3\CMS\ContentBlocks\DataProcessing\ContentBlockData, array returned

### ISSUE THREAD

**Issue by DanielSiepmann** [FriendsOfTYPO3/content-blocks#69]
The issue results from referencing tables not maintained by content blocks, e.g. be_users. We add the following to one of our content blocks (a Page):

```yaml
name: 'codappix/blogpost'
typeName: 1704633691
prefixFields: true
prefixType: 'vendor'
fields:
    -
        identifier: 'author'
        type: 'Select'
        renderType: 'selectSingle'
        foreign_table: 'be_users'
        foreign_table_where: 'be_users.{#lastlogin} > 0'
        minitems: 1
        items:
            -
                label: 'LLL:EXT:site_codappix/ContentBlocks/PageTypes/blogpost/Source/Language/Labels.xlf:author.default.label'
                value: ''
```

It is a bit strange that it works for sys_categorie:

```yaml
    -
        identifier: 'technologies'
        type: 'Select'
        renderType: 'selectMultipleSideBySide'
        foreign_table: 'sys_category'
        foreign_table_where: 'AND {#sys_category}.{#parent} = ###SITE:settings.parentPids.categoryTechnologies###'
        minitems: 1
        fieldControl:
            editPopup:
                disabled: false
            addRecord:
                disabled: false
                options:
                    table: 'sys_category'
                    pid: '###PAGE_TSCONFIG_ID###'
                    setValue: 'append'
```

I guess this is only an issue with the proper type hint within the method signature? As `transformSelectMultipleRelation` always returns an array but `transformSelectSingleRelation` always should return an `ContentBlockData` instance, while it returns an array in case it doesn't know the table.

But it would be cool to also support other tables, e.g. resolve the file relation of be_users, etc.
