### ISSUE TITLE
Allow to use existing field of type input as select

### ISSUE THREAD

**Issue by DanielSiepmann** [FriendsOfTYPO3/content-blocks#70]
We wanted to use the author field of pages but as a select. This doesn't seem possible right now. Our yaml:
```yaml
    -
        identifier: 'author'
        useExistingField: true
        type: 'Select'
        renderType: 'selectSingle'
        foreign_table: 'be_users'
        foreign_table_where: 'be_users.{#lastlogin} > 0'
        minitems: 1
        items:
            -
                label: 'LLL:EXT:site_codappix/ContentBlocks/PageTypes/blogpost/Source/Language/Labels.xlf:author.default.label'
                value: ''
```

But `columnsOverrides` doesn't include the select or foreign_table, only renderType.
