### ISSUE TITLE
FieldType File has no default for "allowed" option

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#82]
When I create a fieldtype with type File, there is no default provided for the _allowed_ option.

Following EditorInterface.yaml:
```
name: treupo/imagetest
title: treupo/imagetest
description: 'Description for Content Element treupo/imagetest'
group: common
prefixFields: true
prefixType: full
fields:
  -
    identifier: header
    useExistingField: true
    label: 'Custom header label'
  - identifier: imagetest
    useExistingField: false
    type: File
```
The element looks like this:
![Bildschirmfoto 2024-01-15 um 09 15 29](https://github.com/nhovratov/content-blocks/assets/107543296/e75664d0-99f8-4b0d-aa9d-64a3aa2920f0)

I expected to have at least something to be displayed inside the file extensions underneath but it is completely empty. The extensions are displayed, when set in the .yaml file, so this is no error. But it would be great, if a default is provided, when nothing is set inside the .yaml file.

The documentation says, that `common-image-types` is the default: https://docs.typo3.org/m/typo3/reference-tca/12.4/en-us/ColumnsConfig/Type/File/Properties/Allowed.html
