### ISSUE TITLE
Restrict Content Blocks to Sites

### ISSUE THREAD

**Issue by nhovratov** [FriendsOfTYPO3/content-blocks#98]
I saw an interesting feature in `flux` extension. It allows to restrict Content Elements to a specific site. We could do this for Content Blocks as well. Additionally, we could even allow restriction per Extension, as this information is present for each Content Block.

Example site config:

```
content_blocks:
  allowed:
       - vendor/name
       - vendor/name2
  allowedExtensions:
       - my_sitepackage
```
